[book]
title = "Auto-Delete Cookies for Privacy"
authors = ["Josh"]
language = "en"
description = "User guide for the Auto-Delete Cookies for Privacy browser extension"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
